name: CI Process

on:
  push:
    branches: [develop, release/*]
  pull_request:
    branches: [develop, release/*]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkstyle
        run: mvn checkstyle:check

      - name: Test and Coverage
        run: mvn test jacoco:check

      - name: Coverage Report
        run: mvn jacoco:report
